export const WA_CONSTANTS = {
    ARCHIVE_NUX_MAX_VIEWS: 3,
    IMG_THUMB_MAX_EDGE: 100,
    DOC_THUMB_MAX_EDGE: 480,
    VIDEO_THUMB_MAX_EDGE: 480,
    MAX_PORTRAIT_MEDIA_CAPTION_LENGTH: 500,
    MAX_FILES: 30,
    MMS_THUMBNAIL_UPLOAD_TIMEOUT: 10000,
    FREQUENTLY_FORWARDED_SENTINEL: 127,
    MAX_SMB_LABEL_COUNT: 20,
    DEFAULT_SMB__NEW_LABEL_COLOR: '#d6d7d7',
    FB_CLB_TOKEN: '1063127757113399|745146ffa34413f9dbb5469f5370b7af',
    FB_CLB_CHECK_URL: 'https://crashlogs.whatsapp.net/wa_fls_upload_check',
    FB_CLB_URL: 'https://crashlogs.whatsapp.net/wa_clb_data',
    FAKE_USER_AGENT: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36',
    G_MAPS_DIR_URL: 'https://maps.google.com/maps/dir',
    G_MAPS_IMG_URL: 'https://maps.googleapis.com/maps/api/staticmap',
    G_MAPS_SEARCH_URL: 'https://maps.google.com/maps/search',
    G_MAPS_URL: 'https://maps.google.com/maps',
    G_MAPS_DARK_MODE_STYLE:
        'style=element:geometry%7Ccolor:0x212121&style=element:labels.icon%7Cvisibility:off&style=element:labels.text.fill%7Ccolor:0x757575&style=element:labels.text.stroke%7Ccolor:0x212121&style=feature:administrative%7Celement:geometry%7Ccolor:0x757575&style=feature:administrative.country%7Celement:labels.text.fill%7Ccolor:0x9e9e9e&style=feature:administrative.land_parcel%7Cvisibility:off&style=feature:administrative.locality%7Celement:labels.text.fill%7Ccolor:0xbdbdbd&style=feature:poi%7Celement:labels.text.fill%7Ccolor:0x757575&style=feature:poi.park%7Celement:geometry%7Ccolor:0x181818&style=feature:poi.park%7Celement:labels.text.fill%7Ccolor:0x616161&style=feature:poi.park%7Celement:labels.text.stroke%7Ccolor:0x1b1b1b&style=feature:road%7Celement:geometry.fill%7Ccolor:0x2c2c2c&style=feature:road%7Celement:labels.text.fill%7Ccolor:0x8a8a8a&style=feature:road.arterial%7Celement:geometry%7Ccolor:0x373737&style=feature:road.highway%7Celement:geometry%7Ccolor:0x3c3c3c&style=feature:road.highway.controlled_access%7Celement:geometry%7Ccolor:0x4e4e4e&style=feature:road.local%7Celement:labels.text.fill%7Ccolor:0x616161&style=feature:transit%7Celement:labels.text.fill%7Ccolor:0x757575&style=feature:water%7Celement:geometry%7Ccolor:0x000000&style=feature:water%7Celement:labels.text.fill%7Ccolor:0x3d3d3d',
    FB_LEGAL_TERMS_URL: 'https://www.facebook.com/legal/terms',
    FB_COMMERCE_POLICY_URL: 'https://www.facebook.com/policies/commerce',
    WA_COMMERCE_POLICY_URL: 'https://www.whatsapp.com/policies/commerce-policy',
    NOTIFICATION_PROMPT_DELAY: 10000,
    PTT_PLAYBACK_DELAY: 400,
    NOTIFICATION_TIMEOUT: 5000,
    CALL_NOTIFICATION_TIMEOUT: 45000,
    IDLE_TIMEOUT: 60000,
    IDLE_TIMEOUT_WAIT: 780000,
    SEARCH_ZOOM: 17,
    SEND_UNAVAILABLE_WAIT: 15000,
    SEND_PAUSED_WAIT: 2500,
    CLEAR_CHAT_DIRTY_WAIT: 2500,
    LOG_UPLOAD_INTERVAL: 3600000,
    REVOKE_WINDOW: 4096,
    ALBUM_DIFF_INTERVAL: 600,
    MAX_TXT_MSG_SIZE: 65536,
    INITIAL_PAGE_SIZE: 768,
    FREQUENTLY_FORWARDED_INITIAL_PAGE_SIZE: 308,
    SUBSEQUENT_PAGE_SIZE: 3072,
    OVERFLOWING_PAGE_THRESHOLD: 0.1,
    GROUP_DESCRIPTION_INFO_PANEL_TRUNC_LENGTH: 100,
    BUSINESS_DESCRIPTION_INFO_PANEL_TRUNC_LENGTH: 200,
    GROUP_DESCRIPTION_LENGTH: 0,
    INFO_DRAWER_MAX_ROWS: 10,
    INFO_DRAWER_MAX_ROWS_IN_COLLAPSED_LIST: 11,
    NUM_COLORS: 20,
    FTS_MIN_CHARS: 2,
    FTS_TTL: 60000,
    FTS_TYPING_DELAY: 300,
    FTS_NUM_RESULTS: 30,
    HSM_ASPECT_RATIO: 1.91,
    TEMPLATE_DOC_MIME_TYPES: 1,
    TEMPLATE_URL_START: 64,
    TEMPLATE_URL_END: 32,
    KEY_STORAGE_TEST: 'storage_test',
    KEY_CLIENT_TOKEN: 'WAToken1',
    KEY_SERVER_TOKEN: 'WAToken2',
    KEY_SECRET: 'WASecretKey',
    KEY_SECRET_BUNDLE: 'WASecretBundle',
    KEY_SECURITY_NOTIFICATIONS: 'WASecurityNotifications',
    KEY_BROWSER_ID: 'WABrowserId',
    KEY_GEOCODER_LOCATION: 'WAGeocoderLocation',
    KEY_GROUP_ASSIGNED_COLOR: 'WAGroupAssignedColor',
    KEY_GMAPS_OVER_LIMIT: 'WAGmapsOverLimit',
    KEY_GLOBAL_MUTE_SOUNDS: 'WAGlobalSounds',
    KEY_OUTGOING_MESSAGE_SOUND: 'WAOutgoingMessageSound',
    KEY_GLOBAL_MUTE_NOTIFICATIONS: 'WAGlobalNotifications',
    KEY_GLOBAL_MUTE_IN_APP_NOTIFICATIONS: 'WAGlobalInAppNotifications',
    KEY_GLOBAL_MUTE_PREVIEWS: 'WAGlobalPreviews',
    KEY_GLOBAL_COLLAPSE_MUTED: 'WAGlobalCollapseMuted',
    KEY_NOTIFICATION_SOUND: 'WANotificationSound',
    KEY_AUTO_DOWNLOAD_PHOTOS: 'WAAutoDownloadPhotos',
    KEY_AUTO_DOWNLOAD_AUDIO: 'WAAutoDownloadAudio',
    KEY_AUTO_DOWNLOAD_VIDEOS: 'WAAutoDownloadVideos',
    KEY_AUTO_DOWNLOAD_DOCUMENTS: 'WAAutoDownloadDocuments',
    KEY_LANG: 'WALangPref',
    KEY_LAST_ACTIVE_EMOJI_TAB: 'WALastActiveEmojiTab',
    KEY_LAST_SELECTED_COMPOSE_BOX_PANEL: 'WALastActiveComposeBoxPanel',
    KEY_LAST_CHAT_MUTE_DURATION: 'WALastChatMuteDuration',
    KEY_UNKNOWN_ID: 'WAUnknownID',
    KEY_VERSION: 'WAVersion',
    KEY_LOAD_RETRY_GENERATION: 'WALoadRetryGeneration',
    KEY_WHATSAPP_MUTEX: 'whatsapp-mutex',
    KEY_LAST_WID: 'last-wid',
    KEY_LAST_WID_MD: 'last-wid-md',
    KEY_SAVE_TO_CAMERA_ROLL: 'save_to_camera_roll',
    KEY_SMB_LABEL_COLOR_PALETTE: 'smb_label_color_palette',
    KEY_LAST_PUSHNAME: 'last-pushname',
    KEY_PROTO_VERSION: 'WAProtoVersion',
    KEY_PTT_PLAYBACK_RATE: 'WAPttPlaybackRate',
    KEY_LOGOUT_DIRTY_BIT: 'post-logout',
    KEY_LOG_PREEMPT_CLEAN_UP: 'WALogPreemptiveCleanUp',
    KEY_PRESERVED_USER_KEYS: 'preserved_user_keys',
    KEY_EMOJI_VARIANT_COLLECTION: 'emoji_variant_collection',
    KEY_RECENT_EMOJI_COLLECTION: 'recent_emoji_collection',
    KEY_CHAT_PREFERENCE_COLLECTION: 'chat_preference',
    LAST_STATUS_USAGE: 'last-status-usage',
    KEY_MD_OPTED_IN: 'md-opted-in',
    KEY_MOBILE_PLATFORM: 'mobile-platform',
    KEY_REMEMBER_ME: 'remember-me',
    KEY_LOGOUT_TOKEN: 'logout-token',
    KEY_OLD_LOGOUT_CREDS: 'old-logout-cred',
    KEY_NO_TAKEOVER: 'no-takeover',
    KEY_WHATSAPP_LS_VERSION: 'ver',
    KEY_WAM_BUFFER: 'wam-buffer',
    KEY_WAM_INFO: 'wam-info',
    KEY_TIME_SPENT_EVENT: 'WaTimeSpentEvent',
    KEY_VIDEO_VOLUME: 'video-volume',
    KEY_VIDEO_MUTE: 'video-mute',
    KEY_CONTACT_CHECKSUM: 'contact-checksum',
    KEY_USER_PRIVACY_SETTINGS: 'user-privacy-settings',
    KEY_IS_SMB: 'is-smb',
    KEY_COMPOSE_CONTENTS_PREFIX: 'compose-contents_',
    KEY_THEME: 'theme',
    KEY_SYSTEM_THEME_MODE: 'system-theme-mode',
    KEY_ABPROPS: 'abprops',
    KEY_HISTORY_SYNC_EARLIEST_DATE: 'history-sync-earliest-date',
    KEY_SYNCD_DISABLED_DUE_TO_FATAL: 'syncd_disabled_due_to_fatal',
    KEY_SYNCD_FIRST_CLEAR_OR_DELETE: 'syncd-first-clear-or-delete',
    KEY_CONTACT_SYNC_REFRESH: 'contact-sync-refresh-seconds',
    COOKIE_REF: 'ref',
    COOKIE_TOK: 'tok',
    PAGE_SIZE: 50,
    MSG_PRELOAD_THRESHOLD: 20,
    MEDIA_QUERY_LIMIT: 50,
    MIN_PIC_SIDE: 192,
    MAX_PIC_SIDE: 640,
    PROF_PIC_THUMB_SIDE: 96,
    MAX_CAPTION_LENGTH: 1024,
    MAX_CART_MESSAGE_LENGTH: 1024,
    MAX_PRODUCT_SUBTITLE_LENGTH: 70,
    MAX_REPLY_PRODUCT_TITLE_LENGTH: 40,
    MAX_REPLY_PRODUCT_DESC_LENGTH: 95,
    ALBUM_MIN_SIZE: 4,
    ALBUM_MAX_SIZE: 102,
    ALBUM_MAX_HEIGHT: 168,
    ALBUM_PADDING: 3,
    PRESENCE_COMPOSING_TIMEOUT: 25000,
    PRESENCE_RESEND_WAIT: 10000,
    MIMETYPE_OGG: 'audio/ogg',
    IMAGE_MIMES: 'image/*',
    WEBP_MIMES: 'image/webp',
    VIDEO_MIMES: 'video/mp4,video/3gpp,video/quicktime',
    KEY_LOG_CURSOR: 'debugCursor',
    MAX_STATUS_LENGTH: 139,
    MAX_PUSHNAME_LENGTH: 25,
    DISP_TYPE: {
        CONVERSATION: 'CONVERSATION',
        MSG_INFO: 'MSG_INFO',
        STARRED_MSGS: 'STARRED_MSGS',
        GALLERY: 'GALLERY',
        REPLY_STAGE: 'REPLY_STAGE',
        QUOTED_MSG: 'QUOTED_MSG',
        CONTACT_CARD: 'CONTACT_CARD',
        ORDER: 'ORDER',
    },
    SEND_LOGS_MAX_EMAIL_LENGTH: 320,
    SEND_LOGS_MAX_SUBJECT_LENGTH: 50,
    SEND_LOGS_MIN_DESC_LENGTH: 10,
    SEND_LOGS_MAX_DESC_LENGTH: 500,
    SEND_LOGS_MAX_SCREENSHOTS: 3,
    SEND_LOGS_MAX_SCREENSHOT_SIZE: 10485760,
    CONTACT_US_MIN_DESC_LENGTH: 10,
    CONTACT_US_MAX_DESC_LENGTH: 5000,
    ACK: { MD_DOWNGRADE: -7, INACTIVE: -6, CONTENT_UNUPLOADABLE: -5, CONTENT_TOO_BIG: -4, CONTENT_GONE: -3, EXPIRED: -2, FAILED: -1, CLOCK: 0, SENT: 1, RECEIVED: 2, READ: 3, PLAYED: 4, PEER: 5 },
    ACK_STRING: { SENDER: 'sender', DELIVERY: 'delivery', READ: 'read', PLAYED: 'played', INACTIVE: 'inactive' },
    RETRY: { VALIDATE_OLD_SESSION: 2, MAX_RETRY: 5 },
    KEY_BUNDLE_TYPE: '\\u0005',
    EDIT_ATTR: { REVOKE: 7 },
    DEVICE: { PRIMARY_DEVICE: 0, PRIMARY_VERSION: 0 },
    BATTERY_LOW_THRESHOLD_1: 15,
    BATTERY_LOW_THRESHOLD_2: 5,
    BATTERY_DELAY: 10000,
    SOCKET_STATE: {
        OPENING: 'OPENING',
        PAIRING: 'PAIRING',
        UNPAIRED: 'UNPAIRED',
        UNPAIRED_IDLE: 'UNPAIRED_IDLE',
        CONNECTED: 'CONNECTED',
        TIMEOUT: 'TIMEOUT',
        CONFLICT: 'CONFLICT',
        UNLAUNCHED: 'UNLAUNCHED',
        PROXYBLOCK: 'PROXYBLOCK',
        TOS_BLOCK: 'TOS_BLOCK',
        SMB_TOS_BLOCK: 'SMB_TOS_BLOCK',
        DEPRECATED_VERSION: 'DEPRECATED_VERSION',
    },
    SOCKET_STREAM: { DISCONNECTED: 'DISCONNECTED', SYNCING: 'SYNCING', RESUMING: 'RESUMING', CONNECTED: 'CONNECTED' },
    COLLECTION_HAS_SYNCED: 'collection_has_synced',
    NEW_MSG_SENT: 'new_msg_sent',
    DIAGNOSTIC_DELAY: 18000,
    ONE_BY_ONE_TRANS_GIF: 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
    DEFAULT_CHAT_WALLPAPER: 'default_chat_wallpaper',
    L10N_PRIORITY: { SAVED: 6, PHONE: 5, PREVIOUS: 4, URL: 3, BROWSER: 2, DEFAULT: 1 },
    RENDER_CURSOR: { RECENT_AT_TOP: 'recent_at_top', RECENT_AT_BOTTOM: 'recent_at_bottom', CONVERSATION: 'conversation', GROUP_CONVERSATION: 'group_conversation', STARRED_DRAWER: 'starred_drawer' },
    SECURITY_LINK: 'https://www.whatsapp.com/security/',
    SMB_TOS_LEARN_MORE_LINK: 'https://www.whatsapp.com/legal/small-business-terms/',
    SERVER_WID: 'server@c.us',
    PSA_WID: '0@c.us',
    STATUS_WID: 'status@broadcast',
    OFFICIAL_BIZ_WID: '16505361212@c.us',
    VISIBILITY: { ABOVE: 'above', VISIBLE: 'visible', BELOW: 'below' },
    VIDEO_STREAM_URL: '/stream/video',
    SPELL_CHECK_SKIP_WORDS: { en_us: {}, en_gb: {}, en: {} },
    GROUP_INVITE_LINK_URL: 'https://chat.whatsapp.com/',
    GROUP_SETTING_TYPE: { ANNOUNCEMENT: 'announcement', RESTRICT: 'restrict', NO_FREQUENTLY_FORWARDED: 'no_frequently_forwarded', EPHEMERAL: 'ephemeral' },
    GROUP_SETTING_TO_METADATA: { announcement: 'announce', restrict: 'restrict', no_frequently_forwarded: 'noFrequentlyForwarded', ephemeral: 'ephemeralDuration' },
    L10N: { DEFAULT: 'en' },
    EMOJI: {
        BUCKET_SIZE: 25,
        CATEGORIES: {
            SMILEYS_PEOPLE: 'SMILEYS_PEOPLE',
            ANIMALS_NATURE: 'ANIMALS_NATURE',
            FOOD_DRINK: 'FOOD_DRINK',
            ACTIVITY: 'ACTIVITY',
            TRAVEL_PLACES: 'TRAVEL_PLACES',
            OBJECTS: 'OBJECTS',
            SYMBOLS: 'SYMBOLS',
            FLAGS: 'FLAGS',
        },
        CATEGORY_MAPPING: {
            'Smileys & People': 'SMILEYS_PEOPLE',
            'Animals & Nature': 'ANIMALS_NATURE',
            'Food & Drink': 'FOOD_DRINK',
            Activity: 'ACTIVITY',
            'Travel & Places': 'TRAVEL_PLACES',
            Objects: 'OBJECTS',
            Symbols: 'SYMBOLS',
            Flags: 'FLAGS',
        },
        ORDERED_CATEGORY_IDS: ['SMILEYS_PEOPLE', 'ANIMALS_NATURE', 'FOOD_DRINK', 'ACTIVITY', 'TRAVEL_PLACES', 'OBJECTS', 'SYMBOLS', 'FLAGS'],
        EMOJI_TYPE: { APPLE: 'APPLE', WHATSAPP: 'WHATSAPP' },
        LARGE_EMOJI_BASE_PATH: '/img',
        LARGE_EMOJI_ELECTRON_BASE_PATH: 'img',
        EMOJI_SPRITES_BASE_PATH: '/img',
        EMOJI_SPRITES_ELECTRON_BASE_PATH: 'img',
    },
    SYSTEM_MESSAGE_TYPES: ['notification', 'notification_template', 'group_notification', 'gp2', 'broadcast_notification', 'e2e_notification', 'call_log', 'protocol'],
    MSG_TYPE: {
        NOTIFICATION: 'notification',
        NOTIFICATION_TEMPLATE: 'notification_template',
        GROUP_NOTIFICATION: 'group_notification',
        GP2: 'gp2',
        BROADCAST_NOTIFICATION: 'broadcast_notification',
        E2E_NOTIFICATION: 'e2e_notification',
        CALL_LOG: 'call_log',
        PROTOCOL: 'protocol',
        CHAT: 'chat',
        LOCATION: 'location',
        PAYMENT: 'payment',
        VCARD: 'vcard',
        CIPHERTEXT: 'ciphertext',
        MULTI_VCARD: 'multi_vcard',
        REVOKED: 'revoked',
        OVERSIZED: 'oversized',
        GROUPS_V4_INVITE: 'groups_v4_invite',
        HSM: 'hsm',
        TEMPLATE_BUTTON_REPLY: 'template_button_reply',
        DEBUG: 'debug',
        IMAGE: 'image',
        VIDEO: 'video',
        AUDIO: 'audio',
        PTT: 'ptt',
        STICKER: 'sticker',
        DOCUMENT: 'document',
        PRODUCT: 'product',
        ORDER: 'order',
        LIST: 'list',
        INTERACTIVE: 'interactive',
        LIST_RESPONSE: 'list_response',
        BUTTONS_RESPONSE: 'buttons_response',
        UNKNOWN: 'unknown',
    },
    TEMPLATE_BUTTON_SUBTYPE: { QUICK_REPLY: 'quick_reply', CALL: 'call', URL: 'url' },
    ELECTRON_PREF: { LAST_SAVED_LOCATION: 'lastSavedLocation', CONTENT_SETTINGS: 'contentSettings' },
    TOUCHBAR_MAX_EMOJIS: 8,
    VERIFIED_LEVEL: { UNKNOWN: 0, LOW: 1, HIGH: 2 },
    HOSTNAME: {
        YOUTUBE: 'youtube.com',
        YOUTUBE_MOBILE: 'm.youtube.com',
        YOUTUBE_SHORTENED: 'youtu.be',
        INSTAGRAM: 'instagram.com',
        STREAMABLE: 'streamable.com',
        FACEBOOK: 'facebook.com',
        FBWATCH: 'fbwat.ch',
        FBWATCH_ALT: 'fb.watch',
        LASSOVIDEOS: 'lassovideos.com',
        LASSO_SHORTENED: 'las.so',
        SHARECHAT: 'sharechat.com',
    },
    WHATSAPP_ORIGIN: 'https://whatsapp.com',
    SMB_SEARCH_FILTERS: { UNREAD: 'unread', GROUP: 'group', BROADCAST: 'broadcast' },
    SMB_LABELS: { MAX_LABEL_LENGTH: 100 },
    PRODUCT_INQUIRY_TYPE: 'product_inquiry',
    PRODUCT_LIST_ITEM_HEIGHT: 96,
    LOADABLE_DELAY: 200,
    TAB_ORDERS: {
        CHAT_STARRED_DRAWER: 3,
        CHAT_LIST_SEARCH: 3,
        ARCHIVED_ENTRY_POINT: 4,
        CHAT_LIST: 4,
        CHAT_CONTACT_LIST: 4,
        CHAT_IMAGE_GALLERY: 4,
        CHAT_SEARCH_MSG_LIST: 4,
        PANEL_SEARCH_INPUT: 5,
        COMPOSE_BOX_MENU_BUTTON: 5,
        COMPOSE_BOX_INPUT: 6,
        PTT_BUTTON: 7,
        MESSAGE_LIST: 8,
        CHAT_HEADER_BUTTON: 9,
    },
    SPEEDY_RESUME_MAX_CHATS: 5000,
    MEDIA_VIEWER: { ANIMATION_DURATION: 500, CLOSE_ANIMATION_DURATION: 200, ZOOM_IN_FACTOR: 2 },
    DEFAULT_THEME: 'light',
    LAYOUT_2COLUMNS_MAX_WIDTH: 1024,
    MUTE_ALWAYS_EXPIRATION_SENTINEL: -1,
    ANDROID_LABEL_COLOR_PALETTE: [
        '#FF9485',
        '#64C4FF',
        '#FFD429',
        '#DFAEF0',
        '#99B6C1',
        '#55CCB3',
        '#FF9DFF',
        '#D3A91D',
        '#6D7CCE',
        '#D7E752',
        '#00D0E2',
        '#FFC5C7',
        '#93CEAC',
        '#F74848',
        '#00A0F2',
        '#83E422',
        '#FFAF04',
        '#B5EBFF',
        '#9BA6FF',
        '#9368CF',
    ],
    IPHONE_LABEL_COLOR_PALETTE: [
        '#A62C71',
        '#90A841',
        '#C1A03F',
        '#792138',
        '#AE8774',
        '#F0B330',
        '#B6B327',
        '#C69FCC',
        '#8B6990',
        '#FF8A8C',
        '#54C265',
        '#FF7B6B',
        '#26C4DC',
        '#57C9FF',
        '#74676A',
        '#7E90A3',
        '#5696FF',
        '#6E257E',
        '#7ACBA5',
        '#243640',
    ],
    VOIP_LOG_COLOR: '#aa6627',
    VOIP_MAC_MINIMUM_OS_RELEASE_VERSION: '17.0.0',
    VOIP_WIN_MINIMUM_OS_RELEASE_VERSION: '10.0.18362',
    VOIP_MAX_GROUP_CALL_PARTICIPANTS: 8,
    WAM_SYS_INFO_INIT_DELAY: 5000,
    KEY_NOTICE_BANNER_CLOSED_AT: 'notice-banner-closed-at',
    KEY_NOTICE_ID: 'notice-id',
    MARKED_AS_UNREAD: -1,
    MAS_APP_IDENTIFIER: '57T9237FN3.desktop.WhatsApp',
    RENDER_PROCESS_LOG_PATH: 'render_process_problem_log.txt',
    WEB_IDB_DB_NAMES: {
        __dbnames: '__dbnames',
        fts_storage: 'fts-storage',
        _hsm_storage_DEPRECATED: 'hsm-storage',
        jobs_storage: 'jobs-storage',
        lru_media_storage_idb: 'lru-media-storage-idb',
        model_storage: 'model-storage',
        offd_storage: 'offd-storage',
        signal_storage: 'signal-storage',
        sw: 'sw',
        wawc: 'wawc',
        wawc_db_enc: 'wawc_db_enc',
    },
    REQUIRED_BROWSER_APIS: { getRandomValues: true, subtleCrypto: true, localstorage: true, sessionstorage: true, url: true, websocket: true, worker: true },
    BROWSER_TYPE: { CHROME: 'chrome', CHROMIUM: 'chromium', FIREFOX: 'firefox', SAFARI: 'safari', IE: 'ie', OPERA: 'opera', EDGE: 'edge' },
    BROWSER_LINK: {
        CHROME: '<a href="https://www.google.com/chrome">Google Chrome</a>',
        FIREFOX: '<a href="http://www.firefox.com">Mozilla Firefox</a>',
        OPERA: '<a href="http://www.opera.com">Opera</a>',
    },
    OS_TYPE: { WINDOWS: 'windows', MAC: 'mac os', CHROMEOS: 'chromium os' },
    LATEST_HASH: 'e64a52eb4e8660a6184cbd072e0e3b13ae63527c',
    VERSION: { p: 2, s: 2126, t: 14 },
    VERSION_BASE: '2.2126.14',
    VERSION_STR: '2.2126.14',
    DYN_ORIGIN: 'https://web.whatsapp.com/',
    PP_URL: 'https://web.whatsapp.com/pp',
    LOGOUT_URL: 'https://web.whatsapp.com/logout',
    WAM_URL: 'https://web.whatsapp.com/wam',
    GROUP_DEFAULT_ICON: '/img/icon-group-default_92b8a80d57227e2f342bd57ccf6382d8.png',
    USER_DEFAULT_ICON: '/img/icon-user-default_bfb4ec026499f5b2d80e673a1a3a5bd7.png',
    NOTIFICATION_TONE_PATH: '/notification_2a485d84012c106acef03b527bb54635.mp3',
    OUTGOING_MESSAGE_TONE_PATH: '/send_message_98602e277c84944aafc41098fa4dd8d8.m4a',
    PTT_MIDDLE_TONE_PATH: '/sequential-ptt-middle_7fa161964e93db72b8d00ae22189d75f.mp3',
    PTT_END_TONE_PATH: '/sequential-ptt-end_62ed28be622237546fd39f9468a76a49.mp3',
    DRAG_TYPE_FILE: 'Files',
    KEY_LOCAL_TAKEOVER_OK: 'local-takeover-ok',
    SCROLL_FUDGE: 100,
    PERMISSION_ALLOWED: 'granted',
    PERMISSION_DEFAULT: 'default',
    PERMISSION_DENIED: 'denied',
    QR_EDGE: 264,
    NUX: {
        SAFARI_LIMITED_SUPPORT: 'safari_limited_support',
        REVOKE_LEGAL_DISCLAIMER_NUX: 'revoke_legal_disclaimer_nux',
        MESSENGER_ROOM_DIALOG_NEW: 'messenger_room_dialog_new',
        MESSENGER_ROOM_DIALOG_RETURNING: 'messenger_room_dialog_returning',
        MESSENGER_ROOM_DIALOG_FROM_CHATLIST: 'messenger_room_dialog_from_chatlist',
        MESSENGER_ROOM_DIALOG_FROM_ATTACH_DROPDOWN: 'messenger_room_dialog_from_attach_dropdown',
        EPHEMERAL: 'ephemeral',
        EPHEMERAL_VIEW_ONCE: 'ephemeral_view_once',
        EPHEMERAL_VIEW_ONCE_RECEIVER: 'ephemeral_view_once_receiver',
        ARCHIVE: 'archive',
    },
    TEXTSIZE_CLASS_MAP: [
        { scale: -1, classname: 'textsize-small' },
        { scale: -2, classname: 'textsize-xsmall' },
        { scale: -3, classname: 'textsize-xxsmall' },
        { scale: 1, classname: 'textsize-large' },
        { scale: 2, classname: 'textsize-xlarge' },
        { scale: 3, classname: 'textsize-xxlarge' },
    ],
    LIST_HEIGHT_TEXTSIZE_MAP: [
        { scale: -1, height: 64 },
        { scale: -2, height: 58 },
        { scale: -3, height: 52 },
        { scale: 1, height: 72 },
        { scale: 2, height: 72 },
        { scale: 3, height: 72 },
    ],
    MSG_FOCUS_SCROLL_ANIMATION_DURATION: 400,
    WAM_PLATFORM: 'WEB',
    FLB_PLATFORM: 'web',
    APP_ID: 'undefined',
    BUILD_ID: '0',
    CAPABILITY_URL: 'https://web.whatsapp.com/browsers.html',
    STATUS_URL: 'https://web.whatsapp.com/status.json',
    CHECK_UPDATE_URL: 'https://web.whatsapp.com/check-update',
    NOTICE_CONTENT_ENDPOINT_URL: 'https://www.whatsapp.com/user-notice/v1/',
    COOKIE_DOMAIN: '.web.whatsapp.com',
    TICKET_URL: 'https://web.whatsapp.com/web-contact-us',
    GROUP_INVITE_URL: 'https://web.whatsapp.com/invite/icon/',
    GROUP_V4_INVITE_ICON_URL: 'https://web.whatsapp.com/invite/v4/icon/',
    LARGE_EMOJI_URL: 'https://web.whatsapp.com/img/',
    PP_TOK: '/pp',
    PP_REF: '/pp',
    UPLOAD_TO_CLB: 1,
    FLAVOR_TAGS: false,
    WEB_SOCKET_URL: 'wss://web.whatsapp.com/ws',
    CHATD_WEB_SOCKET_URL: 'wss://web.whatsapp.com/ws/chat',
    LOG_SIZE_ELECTRON: 14999,
    LOG_SIZE_WEB: 4999,
    MEMORY_METRIC_INTERVAL: 900000,
    MARK_TRANSLATIONS: false,
    WAM_ENV: 'PROD',
    WRITE_TO_CONSOLE: false,
};
